Sprint 11: Реализовал хранение в H2 + интеграционные тесты репозиториев
Alex-Ivash/java-filmorate pull request #4
Opened 2024-10-19 14:04 UTC by Alex-Ivash

2024-10-20 12:35 UTC, tomattman requested changes
Привет, все отлично, основной момент это запросы на фильмы с джойнами
надо чтобы один - три запроса на любое количество фильмов

2024-10-20 12:35 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handle(final NotFoundException e) {
я бы рекомендовал более детальные имена, которые как то отображают что делает метод, в этом случае, хотя бы какую ошибку они обрабатывают

2024-10-20 12:35 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +    private static final String FIND_BY_ID_QUERY = "SELECT * FROM " + TABLE_NAME + " WHERE id=:id";
мне очень нравится что запросы сделаны через объявление переменной с именем таблицы

2024-10-20 12:35 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +    private static final String FIND_BY_ID_QUERY = "SELECT * FROM " + TABLE_NAME + " WHERE id=:id";
можно было бы обыграть с базовым классом, так как запросы такие будут во всех имплементациях

2024-10-20 12:35 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +    public Optional<Film> find(long id) {
этот запрос должен быть с join для того чтобы получать все данные одним запросом

2024-10-20 12:35 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +        return jdbcClient.sql(FIND_ALL_QUERY)
этот запрос должен быть с Join для того чтобы одним запросом получать сразу с рейтингами и по возможности жанрами

2024-10-20 14:11 UTC, Alex-Ivash commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +    public Optional<Film> find(long id) {
Тут, как и ниже, наставник рекомендовал сделать так.
Сейчас данных мало и такой подход с джоинами оправдан.

Однако, в боевой системе данных может быть очень много, а джоины возвращают кучу "лишней" информации после соединения, что, типо, негативно сказывается на производительности.

Под лишней информацией я имею в виду, например, данные фильма(имя, описание и пр.), записи с этим данными будут повторяться несколько раз, если у фильма несколько жанров, например.

2024-10-20 20:46 UTC, Alex-Ivash commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +    private static final String FIND_BY_ID_QUERY = "SELECT * FROM " + TABLE_NAME + " WHERE id=:id";
Тут мало что можно вынести, не усложнив при этом логику наследования так, чтобы это того стоило.
Внес в базовый класс то, что мог. Возможно, где-то чего-то не заметил.

2024-10-20 20:47 UTC, Alex-Ivash commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handle(final NotFoundException e) {
Порефатчил

2024-10-20 20:47 UTC, Alex-Ivash commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +        return jdbcClient.sql(FIND_ALL_QUERY)
Выше описал

2024-10-21 08:02 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/entity/film/JdbcFilmRepository.java
> +    public Optional<Film> find(long id) {
Привет, не могу наставник рекомендовать именно так, потому что это противоречит нашему чек листу на принятие работы
Тут есть несколько моментов
1) имеет смысл через join добавлять то, что тебе всегда надо будет, тут пример с mpa, жанры можно не добавлять в джойн, потому что тогда да, будет захламление, mpa захламления не создаст
2) когда ты пишешь запрос c join ты можешь ограничить то что он будет возвращать, так что в любом случае мусорной информации не будет
3) это все еще учебный проект, и тут надо показать чем вы умеете пользоваться, и одно из требований показать что вы умеете пользоваться join
4) запросы в базу данных считаются одной из самых долгих операций, и обычно именно их оптимизируют в первую очередь, и в таких случаях чаще считают в первую очередь количество запросов а потом количество данных в них, и тут было бы хорошо уложиться в два запроса для любого количества фильмов
один под фильм с рейтингом, второй под жанры

У тебя сейчас сделано хорошо, единственное что стоит доделать, это добавить join чтобы показать, что умеешь и понимаешь как ими пользоваться

2024-10-21 08:03 UTC, tomattman requested changes
Привет, коммент один, ответ на твой комменты про join

2024-10-21 19:06 UTC, merged